This only takes into consideration of top 50 coins in marketcap value.

#### How to use generate_comparison function####
comparison_date:
    The specific reference date that you want for all other dates to compare to. "YYYY-MM-DD" format. Can use Sys.Date() to get today's date.
    
end_date:
    The furthest date in the time interval you want to compare with. "YYYY-MM-DD" format. Can use Sys.Date() to get today's date.

month_or_day:
    "day" = [DEFAULT] Looks at all the days between the start date and end date.
    "month" = Looks at all the months between the start date and end date

interval:
    Takes a number as the argument. The interval number of months or days the start to end date is divided by. Default value is 1.

type:
    "marketcap" = [DEFAULT] sorts dataset by marketcap (descending).
    "percent" = sorts each column of dataset by the coin with the highest gain since that month.
    "name" = sorts dataset by coin name.
    "nopercent" = sorts dataset by marketcap (descending) without percent or name labels.
    
```{r}
setwd("~/Desktop/Crypto_Analysis-master")
source("custom_functions.R")


Sys.Date()

comparison_date = "2017-12-01"
end_date = "2018-02-05"
month_or_day = "day"
interval = 1
type = "percent"

# Creates datafile of top coin price histories
coin.list = generate_coin.list(comparison_date, end_date, topranks=30) 

# Creates comparison table of top coins
output = generate_comparison(comparison_date, end_date, month_or_day, interval, type)

View(output)
title1 = paste("Percent Change of Top 15 Cryptocurrency Prices Compared to the Prices of", format(comparison_date, format="%B %d, %Y"))
sjPlot::tab_df(output, title1, alternate.rows=TRUE ) 

# Creatse comparison graph of top coins
generate_multigraphs(comparison_date, end_date)

```


